# Generated by Django 6.0.8 on 2026-08-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('text', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('background_color', models.CharField(default='#121215', max_length=20)),
                ('text_color', models.CharField(default='#E5C158', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('cta_text', models.CharField(max_length=100)),
                ('cta_link', models.CharField(max_length=255)),
                ('background_image', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
    ]
