# Generated by Django 6.0.8 on 2026-08-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='image', max_length=20)),
                ('mime_type', models.CharField(default='image/jpeg', max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('PUBLIC_ASSET', 'Public Asset'), ('UPLOADED', 'Uploaded Media')], default='UPLOADED', max_length=20)),
                ('folder', models.CharField(default='General', max_length=100)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
